# Generated by Django 5.1 on 2024-11-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='answer',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='回答内容'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='company',
            field=models.CharField(max_length=100, verbose_name='会社名'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='message',
            field=models.TextField(verbose_name='問い合わせ内容'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='staff',
            field=models.CharField(max_length=100, verbose_name='担当スタッフ'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='store',
            field=models.CharField(max_length=100, verbose_name='店舗名'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='題名'),
        ),
    ]
