# Generated by Django 5.1 on 2025-05-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputapp', '0003_remove_inquiry_company_remove_inquiry_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hobby', models.CharField(max_length=200)),
            ],
        ),
    ]
