# Generated by Django 5.1 on 2025-05-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputapp', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hobby',
        ),
        migrations.AddField(
            model_name='profile',
            name='achievements',
            field=models.TextField(blank=True, null=True, verbose_name='実績・成果'),
        ),
        migrations.AddField(
            model_name='profile',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='その他補足情報'),
        ),
        migrations.AddField(
            model_name='profile',
            name='certifications',
            field=models.TextField(blank=True, null=True, verbose_name='取得資格・認定'),
        ),
        migrations.AddField(
            model_name='profile',
            name='experiences',
            field=models.TextField(blank=True, null=True, verbose_name='開発・研究・活動経験'),
        ),
        migrations.AddField(
            model_name='profile',
            name='faculty',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='学部・学科'),
        ),
        migrations.AddField(
            model_name='profile',
            name='frameworks',
            field=models.TextField(blank=True, null=True, verbose_name='使用可能なフレームワーク・ライブラリ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='future_goals',
            field=models.TextField(blank=True, null=True, verbose_name='将来の目標・志望動機'),
        ),
        migrations.AddField(
            model_name='profile',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='学年'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.TextField(blank=True, null=True, verbose_name='趣味・興味'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hometown',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='出身地'),
        ),
        migrations.AddField(
            model_name='profile',
            name='programming_languages',
            field=models.TextField(blank=True, null=True, verbose_name='使用可能なプログラミング言語'),
        ),
        migrations.AddField(
            model_name='profile',
            name='strengths',
            field=models.TextField(blank=True, null=True, verbose_name='強み・スキル'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tools',
            field=models.TextField(blank=True, null=True, verbose_name='使用可能なツール・サービス'),
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='大学名'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名前'),
        ),
    ]
