# Generated by Django 5.1 on 2025-05-09 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputapp', '0005_remove_profile_hobby_profile_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inputapp.profile'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='message',
            field=models.TextField(verbose_name='メッセージ'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='回答'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='問い合わせ内容'),
        ),
    ]
