# Generated by Django 5.1 on 2025-05-10 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputapp', '0006_inquiry_profile_alter_inquiry_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='メッセージ'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inputapp.profile'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='問い合わせ内容'),
        ),
    ]
